spring.application.name=activoscz
spring.graphql.graphiql.enabled=true
spring.main.allow-bean-definition-overriding=true
spring.data.mongodb.uri=mongodb+srv://milton:CMVkfvcDuGJkntkR@backmongo.xtsracx.mongodb.net/db_activoscz?retryWrites=true&w=majority&appName=backmongo
# App Properties
milton.app.jwtCookieName=milton
milton.app.jwtSecret= ======================Milton=Spring===========================
milton.app.jwtExpirationMs=86400000
graphql.tools.schema-location-pattern=classpath*:graphql/**/*.graphqls
